# 第11章 测试代码

## 1. 测试函数

### 1.1 要点

- **单元测试**用于核实函数的某个方面没有问题
- **测试用例**是一组单元测试
- **全覆盖式测试** 用例包含一整套单元测试，涵盖了各种可能的函数使用方 式。对于大型项目，要实现全覆盖可能很难。通常，最初只要针对代码的重要行为编写测试即可，等项目被广泛使用时再考虑全覆盖。

### 1.2 可通过的测试

```python
# name_funciton.py
def get_formatted_name(first, last):
    """Generate a neatly formatted full name."""

    full_name = first + ' ' + last
    return full_name.title()

```

```python
# names.py
from name_funciton import get_formatted_name


print("Enter 'q' at any time to quit.")
while True:
    first = input("\nPlease give me a first name: ")
    if first == 'q':
        break
    last = input("Please give me a last name: ")
    if last == 'q':
        break

    formatted_name = get_formatted_name(first, last)
    print("\tNeatly formatted name: " + formatted_name + '.')

```

```python
# test_name_function.py
import unittest
from name_funciton import get_formatted_name


class NamesTestCase(unittest.TestCase):
    """用于测试的类名最好让它看起来与要测试的函数相关"""

    def test_first_last_name(self):
        formatted_name = get_formatted_name('janis', 'joplin')
        self.assertEqual(formatted_name, 'Janis Joplin')

unittest.main()

```

结果：

```
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

第1行的句点表明有一个测试通过了。接下来的一行指出Python运行了一个测试，消耗的时间不到0.001秒。最后的OK 表明该测试用例中的所有单元测试都通过了。

### 1.3 不能通过的测试

修改name_funciton.py：

```python
# name_funciton.py
def get_formatted_name(first, middle, last):
    """Generate a neatly formatted full name."""

    full_name = first + ' ' + middle + ' ' + last
    return full_name.title()

```

再进行单元测试，运行test_name_function.py：

```
E
======================================================================
ERROR: test_first_last_name (__main__.NamesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangmimi/Desktop/test_name.py", line 10, in test_first_last_name
    formatted_name = get_formatted_name('janis', 'joplin')
TypeError: get_formatted_name() missing 1 required positional argument: 'last'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

- 第1行输出只有一个字母E，它指出测试用例中有一个单元测试导致了错误。
- 接下来，我们 看到NamesTestCase 中的test_first_last_name() 导致了错误。测试用例包含众多单元测试时，知道哪个测试未通过至关重要。
- 我们看到了一个标准 的traceback，它指出函数调用get_formatted_name('janis', 'joplin') 有问题，因为它缺少一个必不可少的位置实参。
- 我们还看到运行了一个单元测试。
- 最后，还看到了一条消息，它指出整个测试用例都未通过，因为运行该测试用例时发生了一个错误。这条消息位于输出末 尾，让你一眼就能看到——你可不希望为获悉有多少测试未通过而翻阅长长的输出。

### 1.4 测试未通过时怎么办

测试未通过时，不要修改测试，而**应修复导致测试不能通过的代码**：检查刚对函数所做的修改，找出导致函数行为不符合预期的修改。

修改name_funciton.py，将middle设为可选，指定默认值。

```python
# name_funciton.py
def get_formatted_name(first, last, middle=''):
    """Generate a neatly formatted full name."""
    if middle:
        full_name = first + ' ' + middle + ' ' + last
    else:
        full_name = first + ' ' + last

    return full_name.title()
```

### 1.5 添加新测试

```python
# test_name_function.py
import unittest
from name_funciton import get_formatted_name


class NamesTestCase(unittest.TestCase):
    """测试name_function.py """
    """用于测试的类名最好让它看起来与要测试的函数相关"""
    """每个用于测试的方法名必须以test_打头"""

    def test_first_last_name(self):
        """能够正确地处理像Janis Joplin这样的姓名吗？"""

        formatted_name = get_formatted_name(first='janis', last='joplin')
        self.assertEqual(formatted_name, 'Janis Joplin')

    def test_first_last_middle_name(self):
        """能够正确地处理像Wolfgang Amadeus Mozart这样的姓名吗？"""

        formatted_name = get_formatted_name(
            first='wolfgang', middle='amadeus', last='mozart')
        self.assertEqual(formatted_name, 'Wolfgang Amadeus Mozart')

unittest.main()

```

